language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "pQLSPkKfwJ2udl+HciNjIbWrsogGPYp1XHu6cHR2GIecoBYFpdNyejofaXjeDF6+2KThs/DVEnfDFr4WCgqXT+9/eHk02KHF3/zEO2UfGMp24gylrRsaV/Xb1ghZTo9jEj8TUpyjKbydSp8L7jqvSwuFgGUfl+137xBiYsE6UUEvuI7c/Ri5G1wGy0TT8aEDfxXKcjeQXCmJbMmgm9tikLB4bp8jN9c87f7UsAOdyB08dZ7JH1s6PMscYPm2zrD6cKaaQXOqI7aS4olkK4KwDSQqmykiNy9kq3RBzx7BL2b3ooQ+Db7JPr51O8t/PQyUKlkRh7bw3A/BnDrly56FUrTZQGVRyow9VJHfmA+/WUtTAchJvIgDAiHKR6TWUK9I1debFPq3LNXSEPFUMj22BYLk5/OtoAGJq5ZEK8tw4DN2QiaAV3ht2LshRRpjP6miWmymN53QrX2VJKDHuFjJRNIUq/NIYMjoWjr7DkejenyrUZMjJ5mKxHUL7Bm01Z8nQC9V71PifbLH68YcxJiOxzJtVHbbBMOKQWsFcln7CM3u0PrgpE0G9zaRHf3dh3kBfm+LPEjoqLR0srZxT3FcSYxf9/PQMgUxbL6owtY8Nbqak+ASpU+upvjWcHW6WCo2vhmbp4+tRvBnhm7LCHJOFhWJN8NBbKoncGCDxdzDZFI="
